#*******************************************************************************
#.travis.yml
#*******************************************************************************

#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Authors:
#Cedric H. David and Alan D. Snow, 2015-2016, based on initial .yml file by Luke
#A. Winslow


#*******************************************************************************
#System specifications for Travis CI
#*******************************************************************************
sudo: false        #Activates the new Travis CI container-based infrastructure
language: cpp      #Sets the language to C++
addons:
  apt:
    packages:
    - gfortran     #Add Fortran (C and C++ installed by specifying C++ above)
    - bc           #Add Basic Calculator (simple math from command line)


#*******************************************************************************
#Environment variables for different tests on multiple Travis CI workers 
#*******************************************************************************
env:
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_JHM.sh' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_JHM.sh 1 15'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_JHM.sh' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_JHM.sh 16 23'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim1' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 1'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim2' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 2'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim3' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 3'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim4' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 4'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim5' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 5'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim6' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 6'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim7' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 7'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim8' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 8'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim9' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 9'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh sim10' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 10'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh opt' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 11 22'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh opt' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 23 82'
- RTK_PUB_DWNL='./rtk_pub_dwnl_David_etal_2011_HP.sh opt' RTK_PUB_REPR='./rtk_pub_repr_David_etal_2011_HP.sh 83 115'


#*******************************************************************************
#Before installing RAPID
#*******************************************************************************
before_install:

#-------------------------------------------------------------------------------
#Creating directory for installation of libraries used by RAPID
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR
- mkdir ../installz
- cd ../installz
- export INSTALLZ_DIR=$PWD

#-------------------------------------------------------------------------------
#Install prerequisites for RAPID
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR
- ./rapid_install_prereqs.sh -i=$INSTALLZ_DIR

#-------------------------------------------------------------------------------
#Exporting environment variables and adding library-related executables to $PATH
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR
- source ./rapid_specify_varpath.sh $INSTALLZ_DIR


#*******************************************************************************
#Installing RAPID
#*******************************************************************************
install:
- cd $TRAVIS_BUILD_DIR
- cd ./src/
- make rapid


#*******************************************************************************
#Testing RAPID 
#*******************************************************************************
script:
- cd $TRAVIS_BUILD_DIR
- cd ./rtk/
- gfortran -o rtk_run_comp rtk_run_comp.f90 -I $TACC_NETCDF_INC -L $TACC_NETCDF_LIB -lnetcdf
- echo $RTK_PUB_DWNL && $RTK_PUB_DWNL
- echo $RTK_PUB_REPR && $RTK_PUB_REPR
